QT += core gui widgets 3dcore 3drender

CONFIG += c++11 console
CONFIG -= app_bundle
CONFIG += resources_big


DEFINES += QT_DEPRECATED_WARNINGS

SOURCES += main.cpp \
    Window/openglwindow.cpp \
    Logger/logger.cpp \
    GameObject/camera.cpp \
    GameObject/gameobject.cpp \
    GameObject/firstpersoncamera.cpp \
    GameObject/planetest.cpp \
    Controller/inputhandler.cpp \
    Controller/command.cpp \
    Game/scene.cpp \
    Utils/mesh.cpp \
    Component/component.cpp \
    Component/transform.cpp \
    Component/meshrenderer.cpp \
    Utils/material.cpp \
    GameObject/model.cpp \
    Component/rigidbody.cpp \
    Component/programshader.cpp \
    Utils/resourcemanager.cpp \
    external/bullet3-2.87/src/Bullet3Collision/BroadPhaseCollision/b3DynamicBvh.cpp \
    external/bullet3-2.87/src/Bullet3Collision/BroadPhaseCollision/b3DynamicBvhBroadphase.cpp \
    external/bullet3-2.87/src/Bullet3Collision/BroadPhaseCollision/b3OverlappingPairCache.cpp \
    external/bullet3-2.87/src/Bullet3Collision/NarrowPhaseCollision/b3ConvexUtility.cpp \
    external/bullet3-2.87/src/Bullet3Collision/NarrowPhaseCollision/b3CpuNarrowPhase.cpp \
    external/bullet3-2.87/src/Bullet3Common/b3AlignedAllocator.cpp \
    external/bullet3-2.87/src/Bullet3Common/b3Logging.cpp \
    external/bullet3-2.87/src/Bullet3Common/b3Vector3.cpp \
    external/bullet3-2.87/src/Bullet3Dynamics/ConstraintSolver/b3FixedConstraint.cpp \
    external/bullet3-2.87/src/Bullet3Dynamics/ConstraintSolver/b3Generic6DofConstraint.cpp \
    external/bullet3-2.87/src/Bullet3Dynamics/ConstraintSolver/b3PgsJacobiSolver.cpp \
    external/bullet3-2.87/src/Bullet3Dynamics/ConstraintSolver/b3Point2PointConstraint.cpp \
    external/bullet3-2.87/src/Bullet3Dynamics/ConstraintSolver/b3TypedConstraint.cpp \
    external/bullet3-2.87/src/Bullet3Dynamics/b3CpuRigidBodyPipeline.cpp \
    external/bullet3-2.87/src/Bullet3Geometry/b3ConvexHullComputer.cpp \
    external/bullet3-2.87/src/Bullet3Geometry/b3GeometryUtil.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/BroadphaseCollision/b3GpuGridBroadphase.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/BroadphaseCollision/b3GpuParallelLinearBvh.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/BroadphaseCollision/b3GpuParallelLinearBvhBroadphase.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/BroadphaseCollision/b3GpuSapBroadphase.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/Initialize/b3OpenCLUtils.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/b3ContactCache.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/b3ConvexHullContact.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/b3GjkEpa.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/b3OptimizedBvh.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/b3QuantizedBvh.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/b3StridingMeshInterface.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/b3TriangleCallback.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/b3TriangleIndexVertexArray.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/b3VoronoiSimplexSolver.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/ParallelPrimitives/b3BoundSearchCL.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/ParallelPrimitives/b3FillCL.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/ParallelPrimitives/b3LauncherCL.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/ParallelPrimitives/b3PrefixScanCL.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/ParallelPrimitives/b3PrefixScanFloat4CL.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/ParallelPrimitives/b3RadixSort32CL.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/Raycast/b3GpuRaycast.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/b3GpuGenericConstraint.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/b3GpuJacobiContactSolver.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/b3GpuNarrowPhase.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/b3GpuPgsConstraintSolver.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/b3GpuPgsContactSolver.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/b3GpuRigidBodyPipeline.cpp \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/b3Solver.cpp \
    external/bullet3-2.87/src/Bullet3Serialize/Bullet2FileLoader/b3BulletFile.cpp \
    external/bullet3-2.87/src/Bullet3Serialize/Bullet2FileLoader/b3Chunk.cpp \
    external/bullet3-2.87/src/Bullet3Serialize/Bullet2FileLoader/b3DNA.cpp \
    external/bullet3-2.87/src/Bullet3Serialize/Bullet2FileLoader/b3File.cpp \
    external/bullet3-2.87/src/Bullet3Serialize/Bullet2FileLoader/b3Serializer.cpp \
    external/bullet3-2.87/src/BulletCollision/BroadphaseCollision/btAxisSweep3.cpp \
    external/bullet3-2.87/src/BulletCollision/BroadphaseCollision/btBroadphaseProxy.cpp \
    external/bullet3-2.87/src/BulletCollision/BroadphaseCollision/btCollisionAlgorithm.cpp \
    external/bullet3-2.87/src/BulletCollision/BroadphaseCollision/btDbvt.cpp \
    external/bullet3-2.87/src/BulletCollision/BroadphaseCollision/btDbvtBroadphase.cpp \
    external/bullet3-2.87/src/BulletCollision/BroadphaseCollision/btDispatcher.cpp \
    external/bullet3-2.87/src/BulletCollision/BroadphaseCollision/btOverlappingPairCache.cpp \
    external/bullet3-2.87/src/BulletCollision/BroadphaseCollision/btQuantizedBvh.cpp \
    external/bullet3-2.87/src/BulletCollision/BroadphaseCollision/btSimpleBroadphase.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btBoxBoxDetector.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btCollisionDispatcher.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btCollisionDispatcherMt.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btCollisionObject.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btCollisionWorld.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btCollisionWorldImporter.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btGhostObject.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btHashedSimplePairCache.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btInternalEdgeUtility.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btManifoldResult.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btSimulationIslandManager.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btUnionFind.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/SphereTriangleDetector.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btBox2dShape.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btBoxShape.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btCapsuleShape.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btCollisionShape.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btCompoundShape.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btConcaveShape.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btConeShape.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btConvex2dShape.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btConvexHullShape.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btConvexInternalShape.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btConvexPointCloudShape.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btConvexPolyhedron.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btConvexShape.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btConvexTriangleMeshShape.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btCylinderShape.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btEmptyShape.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btHeightfieldTerrainShape.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btMinkowskiSumShape.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btMultiSphereShape.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btOptimizedBvh.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btPolyhedralConvexShape.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btShapeHull.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btSphereShape.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btStaticPlaneShape.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btStridingMeshInterface.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btTetrahedronShape.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btTriangleBuffer.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btTriangleCallback.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btTriangleIndexVertexArray.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btTriangleMesh.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btTriangleMeshShape.cpp \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btUniformScalingShape.cpp \
    external/bullet3-2.87/src/BulletCollision/Gimpact/btContactProcessing.cpp \
    external/bullet3-2.87/src/BulletCollision/Gimpact/btGenericPoolAllocator.cpp \
    external/bullet3-2.87/src/BulletCollision/Gimpact/btGImpactBvh.cpp \
    external/bullet3-2.87/src/BulletCollision/Gimpact/btGImpactCollisionAlgorithm.cpp \
    external/bullet3-2.87/src/BulletCollision/Gimpact/btGImpactQuantizedBvh.cpp \
    external/bullet3-2.87/src/BulletCollision/Gimpact/btGImpactShape.cpp \
    external/bullet3-2.87/src/BulletCollision/Gimpact/btTriangleShapeEx.cpp \
    external/bullet3-2.87/src/BulletCollision/Gimpact/gim_box_set.cpp \
    external/bullet3-2.87/src/BulletCollision/Gimpact/gim_contact.cpp \
    external/bullet3-2.87/src/BulletCollision/Gimpact/gim_memory.cpp \
    external/bullet3-2.87/src/BulletCollision/Gimpact/gim_tri_collision.cpp \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.cpp \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btConvexCast.cpp \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btGjkConvexCast.cpp \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btGjkEpa2.cpp \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.cpp \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.cpp \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.cpp \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btPersistentManifold.cpp \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btPolyhedralContactClipping.cpp \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btRaycastCallback.cpp \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.cpp \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.cpp \
    external/bullet3-2.87/src/BulletDynamics/Character/btKinematicCharacterController.cpp \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btConeTwistConstraint.cpp \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btContactConstraint.cpp \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btFixedConstraint.cpp \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btGearConstraint.cpp \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.cpp \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btGeneric6DofSpring2Constraint.cpp \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.cpp \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btHinge2Constraint.cpp \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btHingeConstraint.cpp \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btNNCGConstraintSolver.cpp \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btPoint2PointConstraint.cpp \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.cpp \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btSliderConstraint.cpp \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.cpp \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btTypedConstraint.cpp \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btUniversalConstraint.cpp \
    external/bullet3-2.87/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp \
    external/bullet3-2.87/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorldMt.cpp \
    external/bullet3-2.87/src/BulletDynamics/Dynamics/btRigidBody.cpp \
    external/bullet3-2.87/src/BulletDynamics/Dynamics/btSimpleDynamicsWorld.cpp \
    external/bullet3-2.87/src/BulletDynamics/Dynamics/btSimulationIslandManagerMt.cpp \
    external/bullet3-2.87/src/BulletDynamics/Featherstone/btMultiBody.cpp \
    external/bullet3-2.87/src/BulletDynamics/Featherstone/btMultiBodyConstraint.cpp \
    external/bullet3-2.87/src/BulletDynamics/Featherstone/btMultiBodyConstraintSolver.cpp \
    external/bullet3-2.87/src/BulletDynamics/Featherstone/btMultiBodyDynamicsWorld.cpp \
    external/bullet3-2.87/src/BulletDynamics/Featherstone/btMultiBodyFixedConstraint.cpp \
    external/bullet3-2.87/src/BulletDynamics/Featherstone/btMultiBodyGearConstraint.cpp \
    external/bullet3-2.87/src/BulletDynamics/Featherstone/btMultiBodyJointLimitConstraint.cpp \
    external/bullet3-2.87/src/BulletDynamics/Featherstone/btMultiBodyJointMotor.cpp \
    external/bullet3-2.87/src/BulletDynamics/Featherstone/btMultiBodyPoint2Point.cpp \
    external/bullet3-2.87/src/BulletDynamics/Featherstone/btMultiBodySliderConstraint.cpp \
    external/bullet3-2.87/src/BulletDynamics/MLCPSolvers/btDantzigLCP.cpp \
    external/bullet3-2.87/src/BulletDynamics/MLCPSolvers/btLemkeAlgorithm.cpp \
    external/bullet3-2.87/src/BulletDynamics/MLCPSolvers/btMLCPSolver.cpp \
    external/bullet3-2.87/src/BulletDynamics/Vehicle/btRaycastVehicle.cpp \
    external/bullet3-2.87/src/BulletDynamics/Vehicle/btWheelInfo.cpp \
    external/bullet3-2.87/src/BulletInverseDynamics/details/MultiBodyTreeImpl.cpp \
    external/bullet3-2.87/src/BulletInverseDynamics/details/MultiBodyTreeInitCache.cpp \
    external/bullet3-2.87/src/BulletInverseDynamics/IDMath.cpp \
    external/bullet3-2.87/src/BulletInverseDynamics/MultiBodyTree.cpp \
    external/bullet3-2.87/src/BulletSoftBody/btDefaultSoftBodySolver.cpp \
    external/bullet3-2.87/src/BulletSoftBody/btSoftBody.cpp \
    external/bullet3-2.87/src/BulletSoftBody/btSoftBodyConcaveCollisionAlgorithm.cpp \
    external/bullet3-2.87/src/BulletSoftBody/btSoftBodyHelpers.cpp \
    external/bullet3-2.87/src/BulletSoftBody/btSoftBodyRigidBodyCollisionConfiguration.cpp \
    external/bullet3-2.87/src/BulletSoftBody/btSoftMultiBodyDynamicsWorld.cpp \
    external/bullet3-2.87/src/BulletSoftBody/btSoftRigidCollisionAlgorithm.cpp \
    external/bullet3-2.87/src/BulletSoftBody/btSoftRigidDynamicsWorld.cpp \
    external/bullet3-2.87/src/BulletSoftBody/btSoftSoftCollisionAlgorithm.cpp \
    external/bullet3-2.87/src/LinearMath/btAlignedAllocator.cpp \
    external/bullet3-2.87/src/LinearMath/btConvexHull.cpp \
    external/bullet3-2.87/src/LinearMath/btConvexHullComputer.cpp \
    external/bullet3-2.87/src/LinearMath/btGeometryUtil.cpp \
    external/bullet3-2.87/src/LinearMath/btPolarDecomposition.cpp \
    external/bullet3-2.87/src/LinearMath/btQuickprof.cpp \
    external/bullet3-2.87/src/LinearMath/btSerializer.cpp \
    external/bullet3-2.87/src/LinearMath/btSerializer64.cpp \
    external/bullet3-2.87/src/LinearMath/btThreads.cpp \
    external/bullet3-2.87/src/LinearMath/btVector3.cpp \
    external/bullet3-2.87/src/clew/clew.c \
    GameObject/thirdpersoncamera.cpp \
    Component/vehiclecomponent.cpp



HEADERS += \
    Window/openglwindow.h \
    Logger/logger.h \
    GameObject/camera.h \
    GameObject/gameobject.h \
    GameObject/firstpersoncamera.h \
    GameObject/planetest.h \
    Controller/inputhandler.h \
    Controller/command.h \
    Game/scene.h \
    Utils/mesh.h \
    Component/component.h \
    Component/transform.h \
    Component/meshrenderer.h \
    Utils/material.h \
    GameObject/model.h \
    Component/rigidbody.h \
    Component/programshader.h \
    Utils/resourcemanager.h \
    external/bullet3-2.87/src/Bullet3Collision/BroadPhaseCollision/shared/b3Aabb.h \
    external/bullet3-2.87/src/Bullet3Collision/BroadPhaseCollision/b3BroadphaseCallback.h \
    external/bullet3-2.87/src/Bullet3Collision/BroadPhaseCollision/b3DynamicBvh.h \
    external/bullet3-2.87/src/Bullet3Collision/BroadPhaseCollision/b3DynamicBvhBroadphase.h \
    external/bullet3-2.87/src/Bullet3Collision/BroadPhaseCollision/b3OverlappingPair.h \
    external/bullet3-2.87/src/Bullet3Collision/BroadPhaseCollision/b3OverlappingPairCache.h \
    external/bullet3-2.87/src/Bullet3Collision/NarrowPhaseCollision/shared/b3BvhSubtreeInfoData.h \
    external/bullet3-2.87/src/Bullet3Collision/NarrowPhaseCollision/shared/b3BvhTraversal.h \
    external/bullet3-2.87/src/Bullet3Collision/NarrowPhaseCollision/shared/b3ClipFaces.h \
    external/bullet3-2.87/src/Bullet3Collision/NarrowPhaseCollision/shared/b3Collidable.h \
    external/bullet3-2.87/src/Bullet3Collision/NarrowPhaseCollision/shared/b3Contact4Data.h \
    external/bullet3-2.87/src/Bullet3Collision/NarrowPhaseCollision/shared/b3ContactConvexConvexSAT.h \
    external/bullet3-2.87/src/Bullet3Collision/NarrowPhaseCollision/shared/b3ContactSphereSphere.h \
    external/bullet3-2.87/src/Bullet3Collision/NarrowPhaseCollision/shared/b3ConvexPolyhedronData.h \
    external/bullet3-2.87/src/Bullet3Collision/NarrowPhaseCollision/shared/b3FindConcaveSatAxis.h \
    external/bullet3-2.87/src/Bullet3Collision/NarrowPhaseCollision/shared/b3FindSeparatingAxis.h \
    external/bullet3-2.87/src/Bullet3Collision/NarrowPhaseCollision/shared/b3MprPenetration.h \
    external/bullet3-2.87/src/Bullet3Collision/NarrowPhaseCollision/shared/b3NewContactReduction.h \
    external/bullet3-2.87/src/Bullet3Collision/NarrowPhaseCollision/shared/b3QuantizedBvhNodeData.h \
    external/bullet3-2.87/src/Bullet3Collision/NarrowPhaseCollision/shared/b3ReduceContacts.h \
    external/bullet3-2.87/src/Bullet3Collision/NarrowPhaseCollision/shared/b3RigidBodyData.h \
    external/bullet3-2.87/src/Bullet3Collision/NarrowPhaseCollision/shared/b3UpdateAabbs.h \
    external/bullet3-2.87/src/Bullet3Collision/NarrowPhaseCollision/b3Config.h \
    external/bullet3-2.87/src/Bullet3Collision/NarrowPhaseCollision/b3Contact4.h \
    external/bullet3-2.87/src/Bullet3Collision/NarrowPhaseCollision/b3ConvexUtility.h \
    external/bullet3-2.87/src/Bullet3Collision/NarrowPhaseCollision/b3CpuNarrowPhase.h \
    external/bullet3-2.87/src/Bullet3Collision/NarrowPhaseCollision/b3RaycastInfo.h \
    external/bullet3-2.87/src/Bullet3Collision/NarrowPhaseCollision/b3RigidBodyCL.h \
    external/bullet3-2.87/src/Bullet3Common/shared/b3Float4.h \
    external/bullet3-2.87/src/Bullet3Common/shared/b3Int2.h \
    external/bullet3-2.87/src/Bullet3Common/shared/b3Int4.h \
    external/bullet3-2.87/src/Bullet3Common/shared/b3Mat3x3.h \
    external/bullet3-2.87/src/Bullet3Common/shared/b3PlatformDefinitions.h \
    external/bullet3-2.87/src/Bullet3Common/shared/b3Quat.h \
    external/bullet3-2.87/src/Bullet3Common/b3AlignedAllocator.h \
    external/bullet3-2.87/src/Bullet3Common/b3AlignedObjectArray.h \
    external/bullet3-2.87/src/Bullet3Common/b3CommandLineArgs.h \
    external/bullet3-2.87/src/Bullet3Common/b3FileUtils.h \
    external/bullet3-2.87/src/Bullet3Common/b3HashMap.h \
    external/bullet3-2.87/src/Bullet3Common/b3Logging.h \
    external/bullet3-2.87/src/Bullet3Common/b3Matrix3x3.h \
    external/bullet3-2.87/src/Bullet3Common/b3MinMax.h \
    external/bullet3-2.87/src/Bullet3Common/b3PoolAllocator.h \
    external/bullet3-2.87/src/Bullet3Common/b3QuadWord.h \
    external/bullet3-2.87/src/Bullet3Common/b3Quaternion.h \
    external/bullet3-2.87/src/Bullet3Common/b3Random.h \
    external/bullet3-2.87/src/Bullet3Common/b3ResizablePool.h \
    external/bullet3-2.87/src/Bullet3Common/b3Scalar.h \
    external/bullet3-2.87/src/Bullet3Common/b3StackAlloc.h \
    external/bullet3-2.87/src/Bullet3Common/b3Transform.h \
    external/bullet3-2.87/src/Bullet3Common/b3TransformUtil.h \
    external/bullet3-2.87/src/Bullet3Common/b3Vector3.h \
    external/bullet3-2.87/src/Bullet3Dynamics/ConstraintSolver/b3ContactSolverInfo.h \
    external/bullet3-2.87/src/Bullet3Dynamics/ConstraintSolver/b3FixedConstraint.h \
    external/bullet3-2.87/src/Bullet3Dynamics/ConstraintSolver/b3Generic6DofConstraint.h \
    external/bullet3-2.87/src/Bullet3Dynamics/ConstraintSolver/b3JacobianEntry.h \
    external/bullet3-2.87/src/Bullet3Dynamics/ConstraintSolver/b3PgsJacobiSolver.h \
    external/bullet3-2.87/src/Bullet3Dynamics/ConstraintSolver/b3Point2PointConstraint.h \
    external/bullet3-2.87/src/Bullet3Dynamics/ConstraintSolver/b3SolverBody.h \
    external/bullet3-2.87/src/Bullet3Dynamics/ConstraintSolver/b3SolverConstraint.h \
    external/bullet3-2.87/src/Bullet3Dynamics/ConstraintSolver/b3TypedConstraint.h \
    external/bullet3-2.87/src/Bullet3Dynamics/shared/b3ContactConstraint4.h \
    external/bullet3-2.87/src/Bullet3Dynamics/shared/b3ConvertConstraint4.h \
    external/bullet3-2.87/src/Bullet3Dynamics/shared/b3Inertia.h \
    external/bullet3-2.87/src/Bullet3Dynamics/shared/b3IntegrateTransforms.h \
    external/bullet3-2.87/src/Bullet3Dynamics/b3CpuRigidBodyPipeline.h \
    external/bullet3-2.87/src/Bullet3Geometry/b3AabbUtil.h \
    external/bullet3-2.87/src/Bullet3Geometry/b3ConvexHullComputer.h \
    external/bullet3-2.87/src/Bullet3Geometry/b3GeometryUtil.h \
    external/bullet3-2.87/src/Bullet3Geometry/b3GrahamScan2dConvexHull.h \
    external/bullet3-2.87/src/Bullet3OpenCL/BroadphaseCollision/kernels/gridBroadphaseKernels.h \
    external/bullet3-2.87/src/Bullet3OpenCL/BroadphaseCollision/kernels/parallelLinearBvhKernels.h \
    external/bullet3-2.87/src/Bullet3OpenCL/BroadphaseCollision/kernels/sapKernels.h \
    external/bullet3-2.87/src/Bullet3OpenCL/BroadphaseCollision/b3GpuBroadphaseInterface.h \
    external/bullet3-2.87/src/Bullet3OpenCL/BroadphaseCollision/b3GpuGridBroadphase.h \
    external/bullet3-2.87/src/Bullet3OpenCL/BroadphaseCollision/b3GpuParallelLinearBvh.h \
    external/bullet3-2.87/src/Bullet3OpenCL/BroadphaseCollision/b3GpuParallelLinearBvhBroadphase.h \
    external/bullet3-2.87/src/Bullet3OpenCL/BroadphaseCollision/b3GpuSapBroadphase.h \
    external/bullet3-2.87/src/Bullet3OpenCL/BroadphaseCollision/b3SapAabb.h \
    external/bullet3-2.87/src/Bullet3OpenCL/Initialize/b3OpenCLInclude.h \
    external/bullet3-2.87/src/Bullet3OpenCL/Initialize/b3OpenCLUtils.h \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/kernels/bvhTraversal.h \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/kernels/mpr.cl \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/kernels/mprKernels.h \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/kernels/primitiveContacts.cl \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/kernels/primitiveContacts.h \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/kernels/satClipHullContacts.cl \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/kernels/satClipHullContacts.h \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/kernels/satConcaveKernels.h \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/kernels/satKernels.h \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/b3BvhInfo.h \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/b3ContactCache.h \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/b3ConvexHullContact.h \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/b3ConvexPolyhedronCL.h \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/b3GjkEpa.h \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/b3OptimizedBvh.h \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/b3QuantizedBvh.h \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/b3StridingMeshInterface.h \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/b3SupportMappings.h \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/b3TriangleCallback.h \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/b3TriangleIndexVertexArray.h \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/b3VectorFloat4.h \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/b3VoronoiSimplexSolver.h \
    external/bullet3-2.87/src/Bullet3OpenCL/ParallelPrimitives/kernels/BoundSearchKernelsCL.h \
    external/bullet3-2.87/src/Bullet3OpenCL/ParallelPrimitives/kernels/CopyKernelsCL.h \
    external/bullet3-2.87/src/Bullet3OpenCL/ParallelPrimitives/kernels/FillKernelsCL.h \
    external/bullet3-2.87/src/Bullet3OpenCL/ParallelPrimitives/kernels/PrefixScanKernelsCL.h \
    external/bullet3-2.87/src/Bullet3OpenCL/ParallelPrimitives/kernels/PrefixScanKernelsFloat4CL.h \
    external/bullet3-2.87/src/Bullet3OpenCL/ParallelPrimitives/kernels/RadixSort32KernelsCL.h \
    external/bullet3-2.87/src/Bullet3OpenCL/ParallelPrimitives/b3BoundSearchCL.h \
    external/bullet3-2.87/src/Bullet3OpenCL/ParallelPrimitives/b3BufferInfoCL.h \
    external/bullet3-2.87/src/Bullet3OpenCL/ParallelPrimitives/b3FillCL.h \
    external/bullet3-2.87/src/Bullet3OpenCL/ParallelPrimitives/b3LauncherCL.h \
    external/bullet3-2.87/src/Bullet3OpenCL/ParallelPrimitives/b3OpenCLArray.h \
    external/bullet3-2.87/src/Bullet3OpenCL/ParallelPrimitives/b3PrefixScanCL.h \
    external/bullet3-2.87/src/Bullet3OpenCL/ParallelPrimitives/b3PrefixScanFloat4CL.h \
    external/bullet3-2.87/src/Bullet3OpenCL/ParallelPrimitives/b3RadixSort32CL.h \
    external/bullet3-2.87/src/Bullet3OpenCL/Raycast/kernels/rayCastKernels.h \
    external/bullet3-2.87/src/Bullet3OpenCL/Raycast/b3GpuRaycast.h \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/kernels/batchingKernels.cl \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/kernels/batchingKernels.h \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/kernels/batchingKernelsNew.cl \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/kernels/batchingKernelsNew.h \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/kernels/integrateKernel.cl \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/kernels/integrateKernel.h \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/kernels/jointSolver.h \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/kernels/solveContact.h \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/kernels/solveFriction.h \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/kernels/solverSetup.cl \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/kernels/solverSetup.h \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/kernels/solverSetup2.cl \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/kernels/solverSetup2.h \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/kernels/solverUtils.cl \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/kernels/solverUtils.h \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/kernels/updateAabbsKernel.cl \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/kernels/updateAabbsKernel.h \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/b3GpuConstraint4.h \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/b3GpuGenericConstraint.h \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/b3GpuJacobiContactSolver.h \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/b3GpuNarrowPhase.h \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/b3GpuNarrowPhaseInternalData.h \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/b3GpuPgsConstraintSolver.h \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/b3GpuPgsContactSolver.h \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/b3GpuRigidBodyPipeline.h \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/b3GpuRigidBodyPipelineInternalData.h \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/b3GpuSolverBody.h \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/b3GpuSolverConstraint.h \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/b3Solver.h \
    external/bullet3-2.87/src/Bullet3Serialize/Bullet2FileLoader/autogenerated/bullet2.h \
    external/bullet3-2.87/src/Bullet3Serialize/Bullet2FileLoader/b3BulletFile.h \
    external/bullet3-2.87/src/Bullet3Serialize/Bullet2FileLoader/b3Chunk.h \
    external/bullet3-2.87/src/Bullet3Serialize/Bullet2FileLoader/b3Common.h \
    external/bullet3-2.87/src/Bullet3Serialize/Bullet2FileLoader/b3Defines.h \
    external/bullet3-2.87/src/Bullet3Serialize/Bullet2FileLoader/b3DNA.h \
    external/bullet3-2.87/src/Bullet3Serialize/Bullet2FileLoader/b3File.h \
    external/bullet3-2.87/src/Bullet3Serialize/Bullet2FileLoader/b3Serializer.h \
    external/bullet3-2.87/src/BulletCollision/BroadphaseCollision/btAxisSweep3.h \
    external/bullet3-2.87/src/BulletCollision/BroadphaseCollision/btAxisSweep3Internal.h \
    external/bullet3-2.87/src/BulletCollision/BroadphaseCollision/btBroadphaseInterface.h \
    external/bullet3-2.87/src/BulletCollision/BroadphaseCollision/btBroadphaseProxy.h \
    external/bullet3-2.87/src/BulletCollision/BroadphaseCollision/btCollisionAlgorithm.h \
    external/bullet3-2.87/src/BulletCollision/BroadphaseCollision/btDbvt.h \
    external/bullet3-2.87/src/BulletCollision/BroadphaseCollision/btDbvtBroadphase.h \
    external/bullet3-2.87/src/BulletCollision/BroadphaseCollision/btDispatcher.h \
    external/bullet3-2.87/src/BulletCollision/BroadphaseCollision/btOverlappingPairCache.h \
    external/bullet3-2.87/src/BulletCollision/BroadphaseCollision/btOverlappingPairCallback.h \
    external/bullet3-2.87/src/BulletCollision/BroadphaseCollision/btQuantizedBvh.h \
    external/bullet3-2.87/src/BulletCollision/BroadphaseCollision/btSimpleBroadphase.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btBoxBoxDetector.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btCollisionConfiguration.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btCollisionCreateFunc.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btCollisionDispatcher.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btCollisionDispatcherMt.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btCollisionObject.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btCollisionObjectWrapper.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btCollisionWorld.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btCollisionWorldImporter.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btGhostObject.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btHashedSimplePairCache.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btInternalEdgeUtility.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btManifoldResult.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btSimulationIslandManager.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/btUnionFind.h \
    external/bullet3-2.87/src/BulletCollision/CollisionDispatch/SphereTriangleDetector.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btBox2dShape.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btBoxShape.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btCapsuleShape.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btCollisionMargin.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btCollisionShape.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btCompoundShape.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btConcaveShape.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btConeShape.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btConvex2dShape.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btConvexHullShape.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btConvexInternalShape.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btConvexPointCloudShape.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btConvexPolyhedron.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btConvexShape.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btConvexTriangleMeshShape.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btCylinderShape.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btEmptyShape.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btHeightfieldTerrainShape.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btMaterial.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btMinkowskiSumShape.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btMultiSphereShape.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btOptimizedBvh.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btPolyhedralConvexShape.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btShapeHull.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btSphereShape.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btStaticPlaneShape.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btStridingMeshInterface.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btTetrahedronShape.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btTriangleBuffer.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btTriangleCallback.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btTriangleIndexVertexArray.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btTriangleInfoMap.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btTriangleMesh.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btTriangleMeshShape.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btTriangleShape.h \
    external/bullet3-2.87/src/BulletCollision/CollisionShapes/btUniformScalingShape.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/btBoxCollision.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/btClipPolygon.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/btCompoundFromGimpact.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/btContactProcessing.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/btContactProcessingStructs.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/btGenericPoolAllocator.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/btGeometryOperations.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/btGImpactBvh.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/btGImpactBvhStructs.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/btGImpactCollisionAlgorithm.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/btGImpactMassUtil.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/btGImpactQuantizedBvh.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/btGImpactQuantizedBvhStructs.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/btGImpactShape.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/btQuantization.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/btTriangleShapeEx.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/gim_array.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/gim_basic_geometry_operations.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/gim_bitset.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/gim_box_collision.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/gim_box_set.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/gim_clip_polygon.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/gim_contact.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/gim_geom_types.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/gim_geometry.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/gim_hash_table.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/gim_linear_math.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/gim_math.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/gim_memory.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/gim_radixsort.h \
    external/bullet3-2.87/src/BulletCollision/Gimpact/gim_tri_collision.h \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btComputeGjkEpaPenetration.h \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.h \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btConvexCast.h \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btConvexPenetrationDepthSolver.h \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btDiscreteCollisionDetectorInterface.h \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btGjkCollisionDescription.h \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btGjkConvexCast.h \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btGjkEpa2.h \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btGjkEpa3.h \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.h \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.h \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btManifoldPoint.h \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.h \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btMprPenetration.h \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btPersistentManifold.h \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btPointCollector.h \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btPolyhedralContactClipping.h \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btRaycastCallback.h \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btSimplexSolverInterface.h \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.h \
    external/bullet3-2.87/src/BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.h \
    external/bullet3-2.87/src/BulletDynamics/Character/btCharacterControllerInterface.h \
    external/bullet3-2.87/src/BulletDynamics/Character/btKinematicCharacterController.h \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btConeTwistConstraint.h \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btConstraintSolver.h \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btContactConstraint.h \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btContactSolverInfo.h \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btFixedConstraint.h \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btGearConstraint.h \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.h \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btGeneric6DofSpring2Constraint.h \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.h \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btHinge2Constraint.h \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btHingeConstraint.h \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btJacobianEntry.h \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btNNCGConstraintSolver.h \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btPoint2PointConstraint.h \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.h \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btSliderConstraint.h \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.h \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btSolverBody.h \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btSolverConstraint.h \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btTypedConstraint.h \
    external/bullet3-2.87/src/BulletDynamics/ConstraintSolver/btUniversalConstraint.h \
    external/bullet3-2.87/src/BulletDynamics/Dynamics/btActionInterface.h \
    external/bullet3-2.87/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h \
    external/bullet3-2.87/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorldMt.h \
    external/bullet3-2.87/src/BulletDynamics/Dynamics/btDynamicsWorld.h \
    external/bullet3-2.87/src/BulletDynamics/Dynamics/btRigidBody.h \
    external/bullet3-2.87/src/BulletDynamics/Dynamics/btSimpleDynamicsWorld.h \
    external/bullet3-2.87/src/BulletDynamics/Dynamics/btSimulationIslandManagerMt.h \
    external/bullet3-2.87/src/BulletDynamics/Featherstone/btMultiBody.h \
    external/bullet3-2.87/src/BulletDynamics/Featherstone/btMultiBodyConstraint.h \
    external/bullet3-2.87/src/BulletDynamics/Featherstone/btMultiBodyConstraintSolver.h \
    external/bullet3-2.87/src/BulletDynamics/Featherstone/btMultiBodyDynamicsWorld.h \
    external/bullet3-2.87/src/BulletDynamics/Featherstone/btMultiBodyFixedConstraint.h \
    external/bullet3-2.87/src/BulletDynamics/Featherstone/btMultiBodyGearConstraint.h \
    external/bullet3-2.87/src/BulletDynamics/Featherstone/btMultiBodyJointFeedback.h \
    external/bullet3-2.87/src/BulletDynamics/Featherstone/btMultiBodyJointLimitConstraint.h \
    external/bullet3-2.87/src/BulletDynamics/Featherstone/btMultiBodyJointMotor.h \
    external/bullet3-2.87/src/BulletDynamics/Featherstone/btMultiBodyLink.h \
    external/bullet3-2.87/src/BulletDynamics/Featherstone/btMultiBodyLinkCollider.h \
    external/bullet3-2.87/src/BulletDynamics/Featherstone/btMultiBodyPoint2Point.h \
    external/bullet3-2.87/src/BulletDynamics/Featherstone/btMultiBodySliderConstraint.h \
    external/bullet3-2.87/src/BulletDynamics/Featherstone/btMultiBodySolverConstraint.h \
    external/bullet3-2.87/src/BulletDynamics/MLCPSolvers/btDantzigLCP.h \
    external/bullet3-2.87/src/BulletDynamics/MLCPSolvers/btDantzigSolver.h \
    external/bullet3-2.87/src/BulletDynamics/MLCPSolvers/btLemkeAlgorithm.h \
    external/bullet3-2.87/src/BulletDynamics/MLCPSolvers/btLemkeSolver.h \
    external/bullet3-2.87/src/BulletDynamics/MLCPSolvers/btMLCPSolver.h \
    external/bullet3-2.87/src/BulletDynamics/MLCPSolvers/btMLCPSolverInterface.h \
    external/bullet3-2.87/src/BulletDynamics/MLCPSolvers/btPATHSolver.h \
    external/bullet3-2.87/src/BulletDynamics/MLCPSolvers/btSolveProjectedGaussSeidel.h \
    external/bullet3-2.87/src/BulletDynamics/Vehicle/btRaycastVehicle.h \
    external/bullet3-2.87/src/BulletDynamics/Vehicle/btVehicleRaycaster.h \
    external/bullet3-2.87/src/BulletDynamics/Vehicle/btWheelInfo.h \
    external/bullet3-2.87/src/BulletInverseDynamics/details/IDEigenInterface.hpp \
    external/bullet3-2.87/src/BulletInverseDynamics/details/IDLinearMathInterface.hpp \
    external/bullet3-2.87/src/BulletInverseDynamics/details/IDMatVec.hpp \
    external/bullet3-2.87/src/BulletInverseDynamics/details/MultiBodyTreeImpl.hpp \
    external/bullet3-2.87/src/BulletInverseDynamics/details/MultiBodyTreeInitCache.hpp \
    external/bullet3-2.87/src/BulletInverseDynamics/IDConfig.hpp \
    external/bullet3-2.87/src/BulletInverseDynamics/IDConfigBuiltin.hpp \
    external/bullet3-2.87/src/BulletInverseDynamics/IDConfigEigen.hpp \
    external/bullet3-2.87/src/BulletInverseDynamics/IDErrorMessages.hpp \
    external/bullet3-2.87/src/BulletInverseDynamics/IDMath.hpp \
    external/bullet3-2.87/src/BulletInverseDynamics/MultiBodyTree.hpp \
    external/bullet3-2.87/src/BulletSoftBody/btDefaultSoftBodySolver.h \
    external/bullet3-2.87/src/BulletSoftBody/btSoftBody.h \
    external/bullet3-2.87/src/BulletSoftBody/btSoftBodyConcaveCollisionAlgorithm.h \
    external/bullet3-2.87/src/BulletSoftBody/btSoftBodyData.h \
    external/bullet3-2.87/src/BulletSoftBody/btSoftBodyHelpers.h \
    external/bullet3-2.87/src/BulletSoftBody/btSoftBodyInternals.h \
    external/bullet3-2.87/src/BulletSoftBody/btSoftBodyRigidBodyCollisionConfiguration.h \
    external/bullet3-2.87/src/BulletSoftBody/btSoftBodySolvers.h \
    external/bullet3-2.87/src/BulletSoftBody/btSoftBodySolverVertexBuffer.h \
    external/bullet3-2.87/src/BulletSoftBody/btSoftMultiBodyDynamicsWorld.h \
    external/bullet3-2.87/src/BulletSoftBody/btSoftRigidCollisionAlgorithm.h \
    external/bullet3-2.87/src/BulletSoftBody/btSoftRigidDynamicsWorld.h \
    external/bullet3-2.87/src/BulletSoftBody/btSoftSoftCollisionAlgorithm.h \
    external/bullet3-2.87/src/BulletSoftBody/btSparseSDF.h \
    external/bullet3-2.87/src/clew/clew.h \
    external/bullet3-2.87/src/LinearMath/btAabbUtil2.h \
    external/bullet3-2.87/src/LinearMath/btAlignedAllocator.h \
    external/bullet3-2.87/src/LinearMath/btAlignedObjectArray.h \
    external/bullet3-2.87/src/LinearMath/btConvexHull.h \
    external/bullet3-2.87/src/LinearMath/btConvexHullComputer.h \
    external/bullet3-2.87/src/LinearMath/btCpuFeatureUtility.h \
    external/bullet3-2.87/src/LinearMath/btDefaultMotionState.h \
    external/bullet3-2.87/src/LinearMath/btGeometryUtil.h \
    external/bullet3-2.87/src/LinearMath/btGrahamScan2dConvexHull.h \
    external/bullet3-2.87/src/LinearMath/btHashMap.h \
    external/bullet3-2.87/src/LinearMath/btIDebugDraw.h \
    external/bullet3-2.87/src/LinearMath/btList.h \
    external/bullet3-2.87/src/LinearMath/btMatrix3x3.h \
    external/bullet3-2.87/src/LinearMath/btMatrixX.h \
    external/bullet3-2.87/src/LinearMath/btMinMax.h \
    external/bullet3-2.87/src/LinearMath/btMotionState.h \
    external/bullet3-2.87/src/LinearMath/btPolarDecomposition.h \
    external/bullet3-2.87/src/LinearMath/btPoolAllocator.h \
    external/bullet3-2.87/src/LinearMath/btQuadWord.h \
    external/bullet3-2.87/src/LinearMath/btQuaternion.h \
    external/bullet3-2.87/src/LinearMath/btQuickprof.h \
    external/bullet3-2.87/src/LinearMath/btRandom.h \
    external/bullet3-2.87/src/LinearMath/btScalar.h \
    external/bullet3-2.87/src/LinearMath/btSerializer.h \
    external/bullet3-2.87/src/LinearMath/btSpatialAlgebra.h \
    external/bullet3-2.87/src/LinearMath/btStackAlloc.h \
    external/bullet3-2.87/src/LinearMath/btThreads.h \
    external/bullet3-2.87/src/LinearMath/btTransform.h \
    external/bullet3-2.87/src/LinearMath/btTransformUtil.h \
    external/bullet3-2.87/src/LinearMath/btVector3.h \
    external/bullet3-2.87/src/btBulletCollisionCommon.h \
    external/bullet3-2.87/src/btBulletDynamicsCommon.h \
    GameObject/thirdpersoncamera.h \
    Component/vehiclecomponent.h

RESOURCES += \
    shaders.qrc \
    textures.qrc \
    models.qrc \
    scene.qrc

LIBS += -lopengl32




INCLUDEPATH += $$PWD/external/bullet3-2.87/src
DEPENDPATH += $$PWD/external/bullet3-2.87/bin


unix|win32: LIBS += -L$$PWD/external/bullet3-2.87/bin/ -lBullet3Dynamics_vs2010


unix|win32: LIBS += -L$$PWD/external/bullet3-2.87/bin/ -lBullet3Geometry_vs2010



unix|win32: LIBS += -L$$PWD/external/bullet3-2.87/bin/ -lBullet3Collision_vs2010


unix|win32: LIBS += -L$$PWD/external/bullet3-2.87/bin/ -lBullet3Common_vs2010

unix|win32: LIBS += -L$$PWD/external/bullet3-2.87/bin/ -lBullet3OpenCL_clew_vs2010


unix|win32: LIBS += -L$$PWD/external/bullet3-2.87/bin/ -lLinearMath_vs2010

DISTFILES += \
    external/bullet3-2.87/bin/App_BulletExampleBrowser_vs2010.exp \
    external/bullet3-2.87/bin/App_PhysicsServer_SharedMemory_GUI_vs2010.exp \
    external/bullet3-2.87/bin/App_PhysicsServer_SharedMemory_VR_vs2010.exp \
    external/bullet3-2.87/bin/App_PhysicsServer_SharedMemory_vs2010.exp \
    external/bullet3-2.87/bin/App_PhysicsServerSharedMemoryBridgeTCP_vs2010.exp \
    external/bullet3-2.87/bin/App_PhysicsServerSharedMemoryBridgeUDP_vs2010.exp \
    external/bullet3-2.87/bin/App_RobotSimulator_vs2010.exp \
    external/bullet3-2.87/bin/pybullet_testplugin_vs2010.exp \
    external/bullet3-2.87/bin/pybullet_vrSyncPlugin_vs2010.exp \
    external/bullet3-2.87/bin/pybullet_vs2010.exp \
    external/bullet3-2.87/bin/Test_PhysicsClientTCP_vs2010.exp \
    external/bullet3-2.87/bin/Test_PhysicsClientUDP_vs2010.exp \
    external/bullet3-2.87/bin/Test_PhysicsServerDirect_vs2010.exp \
    external/bullet3-2.87/bin/Test_PhysicsServerInProcessExampleBrowser_vs2010.exp \
    external/bullet3-2.87/bin/Test_PhysicsServerLoopBack_vs2010.exp \
    external/bullet3-2.87/bin/Test_SharedMemoryPhysicsClient_vs2010.exp \
    external/bullet3-2.87/bin/App_BulletExampleBrowser_vs2010.lib \
    external/bullet3-2.87/bin/App_PhysicsServer_SharedMemory_GUI_vs2010.lib \
    external/bullet3-2.87/bin/App_PhysicsServer_SharedMemory_VR_vs2010.lib \
    external/bullet3-2.87/bin/App_PhysicsServer_SharedMemory_vs2010.lib \
    external/bullet3-2.87/bin/App_PhysicsServerSharedMemoryBridgeTCP_vs2010.lib \
    external/bullet3-2.87/bin/App_PhysicsServerSharedMemoryBridgeUDP_vs2010.lib \
    external/bullet3-2.87/bin/App_RobotSimulator_vs2010.lib \
    external/bullet3-2.87/bin/Bullet2FileLoader_vs2010.lib \
    external/bullet3-2.87/bin/Bullet3Collision_vs2010.lib \
    external/bullet3-2.87/bin/Bullet3Common_vs2010.lib \
    external/bullet3-2.87/bin/Bullet3Dynamics_vs2010.lib \
    external/bullet3-2.87/bin/Bullet3Geometry_vs2010.lib \
    external/bullet3-2.87/bin/Bullet3OpenCL_clew_vs2010.lib \
    external/bullet3-2.87/bin/BulletCollision_vs2010.lib \
    external/bullet3-2.87/bin/BulletDynamics_vs2010.lib \
    external/bullet3-2.87/bin/BulletExampleBrowserLib_vs2010.lib \
    external/bullet3-2.87/bin/BulletFileLoader_vs2010.lib \
    external/bullet3-2.87/bin/BulletInverseDynamics_vs2010.lib \
    external/bullet3-2.87/bin/BulletInverseDynamicsUtils_vs2010.lib \
    external/bullet3-2.87/bin/BulletSoftBody_vs2010.lib \
    external/bullet3-2.87/bin/BulletWorldImporter_vs2010.lib \
    external/bullet3-2.87/bin/BussIK_vs2010.lib \
    external/bullet3-2.87/bin/clsocket_vs2010.lib \
    external/bullet3-2.87/bin/ConvexDecomposition_vs2010.lib \
    external/bullet3-2.87/bin/enet_vs2010.lib \
    external/bullet3-2.87/bin/gtest_vs2010.lib \
    external/bullet3-2.87/bin/gwen_vs2010.lib \
    external/bullet3-2.87/bin/HACD_vs2010.lib \
    external/bullet3-2.87/bin/LinearMath_vs2010.lib \
    external/bullet3-2.87/bin/OpenGL_Window_vs2010.lib \
    external/bullet3-2.87/bin/pybullet_testplugin_vs2010.lib \
    external/bullet3-2.87/bin/pybullet_vrSyncPlugin_vs2010.lib \
    external/bullet3-2.87/bin/pybullet_vs2010.lib \
    external/bullet3-2.87/bin/Test_PhysicsClientTCP_vs2010.lib \
    external/bullet3-2.87/bin/Test_PhysicsClientUDP_vs2010.lib \
    external/bullet3-2.87/bin/Test_PhysicsServerDirect_vs2010.lib \
    external/bullet3-2.87/bin/Test_PhysicsServerInProcessExampleBrowser_vs2010.lib \
    external/bullet3-2.87/bin/Test_PhysicsServerLoopBack_vs2010.lib \
    external/bullet3-2.87/bin/Test_SharedMemoryPhysicsClient_vs2010.lib \
    external/bullet3-2.87/bin/vhacd_vs2010.lib \
    external/bullet3-2.87/bin/App_BulletExampleBrowser_vs2010.exe \
    external/bullet3-2.87/bin/App_HelloWorld_vs2010.exe \
    external/bullet3-2.87/bin/App_obj2sdf_vs2010.exe \
    external/bullet3-2.87/bin/App_PhysicsServer_SharedMemory_GUI_vs2010.exe \
    external/bullet3-2.87/bin/App_PhysicsServer_SharedMemory_VR_vs2010.exe \
    external/bullet3-2.87/bin/App_PhysicsServer_SharedMemory_vs2010.exe \
    external/bullet3-2.87/bin/App_PhysicsServerSharedMemoryBridgeTCP_vs2010.exe \
    external/bullet3-2.87/bin/App_PhysicsServerSharedMemoryBridgeUDP_vs2010.exe \
    external/bullet3-2.87/bin/App_PhysicsServerTCP_vs2010.exe \
    external/bullet3-2.87/bin/App_PhysicsServerUDP_vs2010.exe \
    external/bullet3-2.87/bin/App_RobotSimulator_vs2010.exe \
    external/bullet3-2.87/bin/App_SimpleOpenGL3_vs2010.exe \
    external/bullet3-2.87/bin/openvr64pi.dll \
    external/bullet3-2.87/bin/openvr_api.dll \
    external/bullet3-2.87/bin/pybullet_testplugin_vs2010.dll \
    external/bullet3-2.87/bin/pybullet_vrSyncPlugin_vs2010.dll \
    external/bullet3-2.87/bin/pybullet_vs2010.dll \
    external/bullet3-2.87/bin/rtMidiTest_vs2010.exe \
    external/bullet3-2.87/bin/Test_BulletCollision_vs2010.exe \
    external/bullet3-2.87/bin/Test_BulletDynamics_vs2010.exe \
    external/bullet3-2.87/bin/Test_clsocket_EchoServer_vs2010.exe \
    external/bullet3-2.87/bin/Test_clsocket_QueryDayTime_vs2010.exe \
    external/bullet3-2.87/bin/Test_enet_chat_client_vs2010.exe \
    external/bullet3-2.87/bin/Test_enet_chat_server_vs2010.exe \
    external/bullet3-2.87/bin/Test_enet_nat_punchthrough_client_vs2010.exe \
    external/bullet3-2.87/bin/Test_enet_nat_punchthrough_server_vs2010.exe \
    external/bullet3-2.87/bin/Test_Gwen_OpenGL_vs2010.exe \
    external/bullet3-2.87/bin/Test_InverseDynamicsJacobian_vs2010.exe \
    external/bullet3-2.87/bin/Test_InverseDynamicsKinematics_vs2010.exe \
    external/bullet3-2.87/bin/Test_InverseForwardDynamics_vs2010.exe \
    external/bullet3-2.87/bin/Test_LinearMath_vs2010.exe \
    external/bullet3-2.87/bin/Test_OpenCL_Bullet3_vs2010.exe \
    external/bullet3-2.87/bin/Test_PhysicsClientTCP_vs2010.exe \
    external/bullet3-2.87/bin/Test_PhysicsClientUDP_vs2010.exe \
    external/bullet3-2.87/bin/Test_PhysicsServerDirect_vs2010.exe \
    external/bullet3-2.87/bin/Test_PhysicsServerInProcessExampleBrowser_vs2010.exe \
    external/bullet3-2.87/bin/Test_PhysicsServerLoopBack_vs2010.exe \
    external/bullet3-2.87/bin/Test_SharedMemoryPhysicsClient_vs2010.exe \
    external/bullet3-2.87/bin/test_vhacd_vs2010.exe \
    external/bullet3-2.87/src/Bullet3OpenCL/BroadphaseCollision/kernels/gridBroadphase.cl \
    external/bullet3-2.87/src/Bullet3OpenCL/BroadphaseCollision/kernels/parallelLinearBvh.cl \
    external/bullet3-2.87/src/Bullet3OpenCL/BroadphaseCollision/kernels/sap.cl \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/kernels/satConcave.cl \
    external/bullet3-2.87/src/Bullet3OpenCL/ParallelPrimitives/kernels/BoundSearchKernels.cl \
    external/bullet3-2.87/src/Bullet3OpenCL/ParallelPrimitives/kernels/CopyKernels.cl \
    external/bullet3-2.87/src/Bullet3OpenCL/ParallelPrimitives/kernels/FillKernels.cl \
    external/bullet3-2.87/src/Bullet3OpenCL/ParallelPrimitives/kernels/PrefixScanFloat4Kernels.cl \
    external/bullet3-2.87/src/Bullet3OpenCL/ParallelPrimitives/kernels/PrefixScanKernels.cl \
    external/bullet3-2.87/src/Bullet3OpenCL/ParallelPrimitives/kernels/RadixSort32Kernels.cl \
    external/bullet3-2.87/src/Bullet3OpenCL/Raycast/kernels/rayCastKernels.cl \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/kernels/jointSolver.cl \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/kernels/solveContact.cl \
    external/bullet3-2.87/src/Bullet3OpenCL/RigidBody/kernels/solveFriction.cl \
    external/bullet3-2.87/src/Bullet3Collision/CMakeLists.txt \
    external/bullet3-2.87/src/Bullet3Common/CMakeLists.txt \
    external/bullet3-2.87/src/Bullet3Dynamics/CMakeLists.txt \
    external/bullet3-2.87/src/Bullet3Geometry/CMakeLists.txt \
    external/bullet3-2.87/src/Bullet3OpenCL/CMakeLists.txt \
    external/bullet3-2.87/src/Bullet3Serialize/Bullet2FileLoader/CMakeLists.txt \
    external/bullet3-2.87/src/BulletCollision/CMakeLists.txt \
    external/bullet3-2.87/src/BulletDynamics/CMakeLists.txt \
    external/bullet3-2.87/src/BulletInverseDynamics/CMakeLists.txt \
    external/bullet3-2.87/src/BulletSoftBody/CMakeLists.txt \
    external/bullet3-2.87/src/LinearMath/CMakeLists.txt \
    external/bullet3-2.87/src/CMakeLists.txt \
    external/bullet3-2.87/src/Bullet3Collision/premake4.lua \
    external/bullet3-2.87/src/Bullet3Common/premake4.lua \
    external/bullet3-2.87/src/Bullet3Dynamics/premake4.lua \
    external/bullet3-2.87/src/Bullet3Geometry/premake4.lua \
    external/bullet3-2.87/src/Bullet3OpenCL/premake4.lua \
    external/bullet3-2.87/src/Bullet3Serialize/Bullet2FileLoader/premake4.lua \
    external/bullet3-2.87/src/BulletCollision/premake4.lua \
    external/bullet3-2.87/src/BulletDynamics/premake4.lua \
    external/bullet3-2.87/src/BulletInverseDynamics/premake4.lua \
    external/bullet3-2.87/src/BulletSoftBody/premake4.lua \
    external/bullet3-2.87/src/LinearMath/premake4.lua \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/kernels/bvhTraversal.cl \
    external/bullet3-2.87/src/Bullet3OpenCL/NarrowphaseCollision/kernels/sat.cl
